import type {Metadata} from "next";
import React from "react";
import NextTopLoader from "nextjs-toploader";
import {ToastContainer} from "react-toastify";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body>
        <NextTopLoader color={'#f80'} height={2}/>
        {children}
        <ToastContainer/>
        </body>
        </html>
    );
}
